# Generated by Django 4.2.4 on 2023-09-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=100)),
                ('num_pilotos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('num_carro', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotos.equipe')),
            ],
            options={
                'verbose_name_plural': 'Pilotos',
            },
        ),
    ]
